[workspace]
members = [
    # our runnable applications
    "bin/conduit-bin",
    "bin/conduit-web",
    # our dependent library crates
    "crates/conduit-api",
    "crates/conduit-core",
    "crates/conduit-domain",
    "crates/conduit-infrastructure",
]

[profile.release]
debug = true
