version: '3.5'

services:
  postgres:
    container_name: realworld_rust_axum_sqlx_db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"