# fly.toml file generated for realworld-rust-axum-sqlx on 2022-06-21T10:39:28-07:00

app = "realworld-rust-axum-sqlx"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
http_checks = []
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[build]
# we orchestrate three containers using compose, so the naming convention is a bit long
image = "realworld-rust-axum-sqlx_realworld_rust_axum_sqlx_conduit"
