[env] ## tells cargo make that we're in the context of a Cargo workspace
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config] ## we want most/all of our tasks to run in the context of a workspace
default_to_workspace = false

[tasks.dev]
cwd = "./conduit-bin"
command = "cargo"
args = ["run"]
dependencies = ["postgres"]

[tasks.docker]
command = "docker"
args = [
    "compose",
    "-f", "./docker-compose.metrics.yml",
    "-f", "./docker-compose.postgres.yml",
    "-f", "./docker-compose.conduit.yml",
    "up",
    "--build"
]

[tasks.postgres]
command = "docker"
args = [
    "compose",
    "-f", "./docker-compose.metrics.yml",
    "-f", "./docker-compose.postgres.yml",
    "start",
]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.fix]
command = "cargo"
args = ["fix", "--allow-dirty"]

[tasks.lint]
command = "cargo"
args = ["clippy"]

[tasks.lint-staged]
command = "npx"
args = ["lint-staged"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.integration]
command = "./tests/run-postman-tests.sh"
dependencies = ["docker"]

[tasks.migrate] ## ensure Postgres is running, the container has a bit of warmup time causing migrations to fail
cwd = "./conduit-infrastructure"
install_crate = "sqlx"
command = "sqlx"
args = ["migrate", "run"]
dependencies = ["postgres"]

[tasks.refresh-schema]
cwd = "./conduit-infrastructure"
install_crate = "sqlx"
command = "cargo"
args = ["sqlx", "prepare"]

[tasks.pre-commit]
dependencies = [
    "format",
    "lint",
    "test",
]