[package]
name = "conduit-domain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
validator = {version = "0.14.0", features = ["derive"]}