[package]
name = "conduit-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conduit-repository = { path = "../conduit-repository" }
conduit-shared = { path = "../conduit-shared" }

# axum HTTP dependencies
axum = "0.5"
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
tower = "0.4"

# utilty crates
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.81"
rust-argon2 = "0.4.0"
jwt = "0.16.0"
dotenv = "0.15.0"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0.32"
validator = {version = "0.14.0", features = ["derive"]}
thiserror = "1.0"
