name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cargo-make
        uses: dtolnay/rust-toolchain@stable
        run: cargo install --debug cargo-make

      - name: Run CI
        run: cargo make ci
