name: Coverage

on:
  push:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: coverage

    runs-on: ubuntu-latest

    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cargo-make
        uses: dtolnay/rust-toolchain@stable
        run: cargo install --debug cargo-make

      - name: Generate code coverage
        uses: dtolnay/rust-toolchain@stable
        run: cargo make test-coverage

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
